title :  HIREN PATEL
logo : /assests/img/hiren1.PNG
description : Data Analyst | Data Engineer 
theme: jekyll-theme-minimal
show_downloads: false
hide_downloads : true
download_rmd: false
style: |
  .logo {
    margin-left: 10px; /* Adjust the value as needed */
  }
