---
title :  HIREN PATEL
logo : /assests/img/hiren1.PNG
description : Data Analyst | Data Engineer 
theme: jekyll-theme-minimal
show_downloads: false
hide_downloads : true
download_rmd: false
---
<style>
.logo {
  margin-left: 20px;
}
</style>

<div class="logo">
  <img src="/assets/img/hiren.PNG" alt="Logo">
</div>
